name: NothingsVN Oplus ROM Build

on:
  workflow_dispatch:
    inputs:
      input_url:
        description: 'URL of the ROM to build'
        required: true
      
      TOOLBOX:
        description: 'Include Kaorios Toolbox support'
        required: true
        type: boolean
        default: true

      MODROM:
        description: 'Include NT Mods'
        required: true
        type: boolean
        default: true
      
jobs:
  Initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Clean All Unused file,application
        run: |
          docker rmi `docker images -q` || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d || true
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* || true
          sudo apt -y autoremove --purge || true
          sudo apt -y autoclean || true
          sudo apt clean || true

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 1024
          root-reserve-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Set up Time
        run: |
          echo "Setting Vienam timezone"
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh

  Build:
    needs: Initialize
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenJDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup dependency (Install & remove stuff)
        run: |
          sudo bash setup.sh

      # trash code begin
      - name: Config 'config.env' file
        run: |
          work_dir=$(pwd)
          # Toolbox
          if [ "${{ github.event.inputs.TOOLBOX }}" = "false" ]; then
            sed -i 's/^install_toolbox=true/install_toolbox=false/g' config.env
          fi

          # Mod rom
          if [ "${{ github.event.inputs.MODROM }}" = "false" ]; then
            sed -i 's/^install_mods=true/install_mods=false/g' config.env
          fi

          config_mod=$(grep "install_mods" $work_dir/config.env | cut -d '=' -f 2)
          config_toolbox=$(grep "install_toolbox" $work_dir/config.env | cut -d '=' -f 2)

          echo "[CONFIG] - Install NT Mods: ${config_mod}"
          echo "[CONFIG] - Include Kaorios Toolbox support: ${config_toolbox}"
      # trash code end
        
      - name: Giving permission
        run: |
          sudo chmod 777 -R *

      - name: Build ROM...
        env:
          INPUT_URL: ${{ inputs.input_url }}
        run: |
          sudo bash build.sh "$INPUT_URL"

      - name: Pack ROM...
        run: |
          sudo bash packROM.sh n

      - name: Setup Rclone...
        run: |
          sudo -E bash uploadROM.sh setup "${{ secrets.GH_TOKEN }}" "${{ secrets.GH_REPO }}" "${{ secrets.RCLONE_TOKEN_PATH }}"
          
      - name: Upload ROM...
        run: |
          sudo -E bash uploadROM.sh
      
      - name: Update Database and Notificaton to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TG_TOKEN }}
        run: |
          